name: QSRR-Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python
    strategy:
        matrix:
            python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: export PATH=$PATH:/home/runner/.local/bin/$PATH:$pwd
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |

          echo "Running  QSRR test framework"
          
          ROOT_PATH=$(pwd)/../../
          TEST_PATH=$(ROOT_PATH)/tests/

          PYTHON_PATH="$TEST_PATH:$ROOT_PATH"
          
          if [ -z $PYTHONPATH ]; then
              export PYTHONPATH=$PYTHON_PATH
          else
              export PYTHONPATH=$PYTHONPATH:$PYTHON_PATH
          fi

          echo $ROOT_PATH
          echo $TEST_PATH

          coverage run --source $ROOT_PATH/. -m py.test -v $TEST_PATH*
          coverage report -m --omit *test*,*scripts*,*cython_builder*,*__main__*,*de.py*,*notebooks*
