name: QSRR-Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python
    strategy:
        matrix:
            python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: export PATH=$PATH:/home/runner/.local/bin/$PATH:$pwd
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |

            echo "Running  QSRR test framework"
            
            TEST_PATH=$(pwd)
            cd ..
            cd ..
            ROOT_PATH=$(echo $(pwd)/qsrr)
            cd $TEST_PATH
            
            export COVERAGE_PROCESS_START=$(echo $TEST_PATH.coveragerc)
            
            PYTHON_PATH="$(echo $TEST_PATH):$(echo $ROOT_PATH)"
            
            if [ -z $PYTHONPATH ]; then
                export PYTHONPATH=$PYTHON_PATH
            else
                export PYTHONPATH=$PYTHONPATH:$PYTHON_PATH
            fi
            
            echo "$(echo $ROOT_PATH)"
            echo "$(echo $TEST_PATH)"
            echo "$(echo $PYTHONPATH)"
            
            coverage run --source "$(echo $ROOT_PATH)" -m pytest -v "$(echo $TEST_PATH)"
            coverage report -m --omit='*tests*,*notebooks*,*data*'
